2024-06-20 18:06:37,967 - custodian.policy - INFO - policy:ec2-no-tag-name resource:aws.ec2 region:us-east-1 count:1 time:2.51
2024-06-20 18:06:40,202 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/policy.py", line 364, in run
    results = a.process(resources)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/actions/notify.py", line 287, in process
    self.consume_buffer(message, rbuffer)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/actions/notify.py", line 292, in consume_buffer
    receipt = self.send_data_message(message, payload)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/actions/notify.py", line 348, in send_data_message
    return self.send_sqs(message, payload)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/actions/notify.py", line 415, in send_sqs
    result = client.send_message(
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.QueueDoesNotExist: An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the SendMessage operation: The specified queue does not exist.
2024-06-20 18:11:42,819 - custodian.policy - INFO - policy:ec2-no-tag-name resource:aws.ec2 region:us-east-1 count:1 time:0.00
2024-06-20 18:14:09,088 - custodian.policy - INFO - policy:ec2-no-tag-name resource:aws.ec2 region:us-east-1 count:1 time:0.00
2024-06-20 18:14:11,484 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/policy.py", line 364, in run
    results = a.process(resources)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/actions/notify.py", line 287, in process
    self.consume_buffer(message, rbuffer)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/actions/notify.py", line 292, in consume_buffer
    receipt = self.send_data_message(message, payload)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/actions/notify.py", line 348, in send_data_message
    return self.send_sqs(message, payload)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/actions/notify.py", line 415, in send_sqs
    result = client.send_message(
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.QueueDoesNotExist: An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the SendMessage operation: The specified queue does not exist.
2024-06-20 18:44:18,246 - custodian.policy - INFO - policy:ec2-no-tag-name resource:aws.ec2 region:us-east-1 count:3 time:2.78
2024-06-20 18:44:20,697 - custodian.output - ERROR - Error while executing policy
Traceback (most recent call last):
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/policy.py", line 364, in run
    results = a.process(resources)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/actions/notify.py", line 287, in process
    self.consume_buffer(message, rbuffer)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/actions/notify.py", line 292, in consume_buffer
    receipt = self.send_data_message(message, payload)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/actions/notify.py", line 348, in send_data_message
    return self.send_sqs(message, payload)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/c7n/actions/notify.py", line 415, in send_sqs
    result = client.send_message(
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/anand.prakash@happiestminds.com/.local/lib/python3.8/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.QueueDoesNotExist: An error occurred (AWS.SimpleQueueService.NonExistentQueue) when calling the SendMessage operation: The specified queue does not exist.
